#spec:
#  replicas: global.fleet.clusterLabels.management.cattle.io/test.min-replica-count
metadata:
  labels:
    ## This label is applied to the deployment
    #replicas: global.fleet.clusterLabels.min-replica-count
    replicas: todas
